# Supabase configuration
project_id = "your-project-ref"
api_url = "https://your-project.supabase.co"

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "${SUPABASE_API_URL}"

[auth]
enabled = true
site_url = "${VERCEL_URL}"
additional_redirect_urls = ["${VERCEL_URL}", "https://*.vercel.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
password_min_length = 6

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[storage]
enabled = true

[realtime]
enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_functions]
enabled = true

[functions.api]
verify_jwt = true
