# Supabase configuration
project_id = "your-project-ref"
api_url = "https://your-project.supabase.co"

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
password_min_length = 6

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[edge_functions]
enabled = true

[functions.api]
verify_jwt = true
