version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://caraxfinance:password@db:5432/caraxfinance
      - SESSION_SECRET=your-super-secure-session-secret
      - CORS_ORIGIN=https://your-domain.com
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - caraxfinance-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=caraxfinance
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=caraxfinance
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - caraxfinance-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - caraxfinance-network

volumes:
  postgres_data:

networks:
  caraxfinance-network:
    driver: bridge
