version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-caraxfinance}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-caraxfinance}
      SESSION_SECRET: ${SESSION_SECRET:-carax-finance-prod-secret-key}
      JWT_SECRET: ${JWT_SECRET:-carax-finance-jwt-secret-key}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.ethereal.email}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@caraxfinance.com}
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      CONTACT_EMAIL: ${CONTACT_EMAIL:-support@caraxfinance.com}
      SITE_URL: ${SITE_URL:-http://localhost:4000}

volumes:
  postgres_data:
