services:
  - type: web
    name: axix-finance-api
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: axix-finance-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false  # You'll set this manually
      - key: SMTP_PASSWORD
        sync: false  # You'll set this manually
      - key: EMAIL_FROM
        value: support@axix-finance.com
      - key: CLIENT_URL
        value: https://your-domain.vercel.app
      - key: CORS_ORIGIN
        value: https://your-domain.vercel.app
      - key: CONTACT_EMAIL
        value: support@axix-finance.com
    healthCheckPath: /api/health
    
  - type: pserv
    name: axix-finance-db
    env: postgresql
    plan: starter
    databaseName: axix_finance
    databaseUser: axix_user
